const D=window.TPA_DATA;const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const R={CN:'中国赛区',PAC:'太平洋赛区',EMEA:'欧洲、中东及非洲赛区',AMER:'美洲赛区'};
const RC={CN:'CN',PAC:'PACIFIC',EMEA:'EMEA',AMER:'AMER'};
function regionOf(t){for(const [r,a] of Object.entries(D.teams))if(a.includes(t))return r;return ''}
function logo(t){for(const [r,a] of Object.entries(D.teams)){const i=a.indexOf(t);if(i>=0)return `assets/logos/${r.toLowerCase()}_${String(i+1).padStart(2,'0')}.png`}return 'assets/tpa-mark.svg'}
function country(t,p){return D.playerCountry?.[p]||D.teamCountry?.[t]||R[regionOf(t)]||'档案未注明'}
function teamName(t){const aliases={'G2':'G2 ESPORTS','C9':'Cloud9','LEV':'Leviatán','EG':'Evil Geniuses','PRQ':'PaperRex','PGW':'PG WON','MG':'MIC GAMING','E1':'E1 Esports','TH':'Team Heretics','TL':'Team Liquid','KC':'Karmine Corp','VIT':'Team Vitality','FNC':'Fnatic','BLG':'Bilibili Gaming','NRG':'NRG','EDG':'Edward Gaming','JDG':'JDG ESPORTS','NS':'NS','AGAL':'AG.AL','AG.AL':'AG.AL','PRX':'PaperRex','DRX':'Kiwoom DRX'};return aliases[t]||t}
function T(t,small=false){const n=teamName(t);return `<span class="team-inline"><img src="${logo(n)}"><b>${esc(n)}</b></span>`}
function nav(){return `<header class="top"><a class="brand" href="#/"><img src="assets/tpa-mark.svg"><strong>TPA <i>ESPORTS</i></strong></a><nav>${[['/','首页'],['/events','赛事中心'],['/schedule','赛程与赛果'],['/teams','战队'],['/players','选手'],['/rankings','排行榜'],['/history','Past Champion'],['/about','关于我们']].map(x=>`<a href="#${x[0]}">${x[1]}</a>`).join('')}</nav><div class="top-actions">⌕　◎　中文⌄</div></header>`}
function side(){return `<aside><div class="side-title">四大赛区</div>${Object.entries(RC).map(([r,n])=>`<a href="#/teams?region=${r}" class="region-link ${r}"><span>${r}</span><small>${R[r]}</small></a>`).join('')}<div class="side-line"></div><div class="side-title plain">快速入口</div>${[['/schedule','▦','赛事日历'],['/teams','◈','战队列表'],['/players','♙','选手列表'],['/rankings','▥','全球排名'],['/history','♜','历史冠军']].map(x=>`<a class="quick" href="#${x[0]}"><span>${x[1]}</span>${x[2]}</a>`).join('')}<div class="side-foot">TPA ESPORTS<br><small>ONE STAGE. ONE DREAM.</small></div></aside>`}
function shell(body){app.innerHTML=nav()+side()+`<main>${body}</main>`;}
function hero(){return `<section class="hero"><div class="hero-copy"><div class="kicker">TPA CHAMPIONS TOUR</div><h1>GLOBAL FINALS<br><em>2026</em></h1><p>NEW YORK × ALLEN, TX　|　OCT 2026</p><a class="red-btn" href="#/event/finals-allen-2026">查看赛事详情 →</a></div><div class="hero-art"><div class="trophy">✦</div><div class="city">TPA ESPORTS</div></div></section>`}
function match(e,compact=false){return `<div class="match-card"><div class="match-head"><span>${esc(e.stage||'比赛')}</span><b>${esc(e.format||'BO5')}</b></div><div class="match-teams"><div>${T(e.a)}</div><strong>${esc(e.score||'VS')}</strong><div>${T(e.b)}</div></div><div class="match-foot"><span>${esc(e.date||'')}</span><span>${esc(e.status||'')}</span></div></div>`}
function home(){const upcoming=[['Masters Santiago 2026','PRX','EDG','2026-07-18','BO5'],['TCI London 2026','PaperRex','Bilibili Gaming','2026-08-06','BO5'],['Finals 2026','T1','JDG ESPORTS','2026-10-10','BO5']].map((x,i)=>({stage:x[0],a:x[1],b:x[2],date:x[3],format:x[4],score:'VS'}));const recent=[...D.international].filter(e=>e.finalScore).slice(-3).reverse().map(e=>({stage:e.name,a:e.champion,b:e.runner,date:e.year,format:'FINAL',score:e.finalScore,status:'已记录'}));return `<div class="page">${hero()}<div class="dashboard-grid"><section><div class="section-title"><h2>近期赛事</h2><a href="#/schedule">查看全部 →</a></div><div class="match-grid">${upcoming.map(x=>match(x)).join('')}</div><div class="section-title"><h2>最新赛果</h2><a href="#/events">查看全部 →</a></div><div class="match-grid">${recent.map(x=>match(x)).join('')}</div><div class="section-title"><h2>四大赛区战队</h2></div><div class="region-grid">${Object.entries(D.teams).map(([r,a])=>`<a class="region-card ${r}" href="#/teams?region=${r}"><b>${r}</b><span>${R[r]}</span><small>${a.length} 支档案战队</small></a>`).join('')}</div></section><section><div class="panel"><div class="section-title"><h2>战力排名</h2><a href="#/rankings">查看全部 →</a></div>${[['PaperRex','2010'],['Bilibili Gaming','1987'],['Edward Gaming','1956'],['JDG ESPORTS','1923'],['NRG','1897']].map((x,i)=>`<div class="rank-row"><b>${i+1}</b>${T(x[0])}<span>${x[1]}</span><i>${i%2?'▼':'▲'}</i></div>`).join('')}</div><div class="season-card"><b>2026 SEASON</b><span>四大赛区 · 全球联赛 · 国际赛事</span><a href="#/schedule">查看赛程 →</a></div><div class="panel"><div class="section-title"><h2>历史冠军</h2><a href="#/history">查看全部 →</a></div><div class="year-strip">${[...new Set(D.globalHistory.map(x=>x[0]))].sort().map(y=>`<a href="#/history?year=${y}">${y}<small>${D.globalHistory.filter(x=>x[0]===y).length} 场</small></a>`).join('')}</div></div></section></div></div>`}
function events(){return `<div class="page"><div class="page-head"><div><div class="kicker">EVENTS & STANDINGS</div><h1>赛事中心</h1><p>国际赛事、四大赛区赛季和完整淘汰赛结构集中查看。</p></div></div><div class="event-list">${D.international.map(e=>`<a class="event-row" href="#/event/${e.id}"><div class="event-mark">${e.year}</div><div><b>${esc(e.name)}</b><small>${esc(e.city||'')} · ${esc(e.type||'国际赛')}</small></div><div class="event-final">${T(e.champion)}<strong>${esc(e.finalScore||'—')}</strong>${T(e.runner)}</div><span>›</span></a>`).join('')}</div></div>`}
function schedule(){const rows=[['2026-01','TPA KickOff','四大赛区'],['2026-02','MASTERS 2026 Busan','全球大师赛'],['2026-03','TPA Series Stage 1','四大赛区'],['2026-05','TCI 2026 London','季中冠军赛'],['2026-06','SUMMER Transfer','转会期'],['2026-07','MASTERS 2026 Santiago','全球大师赛'],['2026-08','TPA Series Stage 2','四大赛区'],['2026-10','FINALS 2026 New York / Allen, TX','全球总决赛'],['2026-11','WINTER Transfer','转会期'],['2026-12','Draft Conference / All-Star','赛季特别活动']];return `<div class="page"><div class="page-head"><div><div class="kicker">SCHEDULE</div><h1>赛程与赛果</h1><p>按日期、赛事和赛区浏览；进入赛事可以展开逐场对阵。</p></div></div><div class="calendar">${rows.map((x,i)=>`<div class="cal-row"><time>${x[0]}</time><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${i<5?'档案赛程':'赛季安排'}</span></div>`).join('')}</div><div class="section-title"><h2>2024–2026 国际赛</h2></div><div class="match-grid">${D.international.flatMap(e=>[{stage:e.name,a:e.champion,b:e.runner,date:e.year,format:'FINAL',score:e.finalScore,status:'已记录'}]).slice(-9).reverse().map(x=>match(x)).join('')}</div></div>`}
function teams(){return `<div class="page"><div class="page-head"><div><div class="kicker">TEAMS</div><h1>战队档案</h1><p>战队 Logo、所属赛区、完整当前档案选手和国籍信息。</p></div></div>${Object.entries(D.teams).map(([r,a])=>`<section class="team-section"><div class="section-title"><h2>${RC[r]} <small>${R[r]}</small></h2></div><div class="team-grid">${a.map(t=>`<a class="team-card" href="#/team/${encodeURIComponent(t)}"><img src="${logo(t)}"><div><b>${esc(t)}</b><span>${D.teamCountry[t]||R[r]}</span><small>${(D.rosters[t]||[]).length} 名档案选手</small></div></a>`).join('')}</div></section>`).join('')}</div>`}
function team(t){const ps=D.rosters[t]||[];return `<div class="page"><div class="team-hero"><img src="${logo(t)}"><div><div class="kicker">${regionOf(t)} · TEAM PROFILE</div><h1>${esc(t)}</h1><p>${esc(D.teamCountry[t]||R[regionOf(t)]||'')}</p></div></div><div class="section-title"><h2>选手名单</h2><span>${ps.length} 名</span></div><div class="player-grid">${ps.map((p,i)=>`<div class="player-card"><div class="avatar">${esc(p.slice(0,1).toUpperCase())}</div><div><b>${esc(p)}</b><span>${['TOP','JUG','MID','ADC','SUP'][i]||'PLAYER'}</span><small>${esc(country(t,p))}</small></div></div>`).join('')}</div><div class="notice">国籍显示遵循你提供的《TPA战队档案》：能从档案明确对应的国家直接显示；无法从文字层提取旗帜的条目按战队档案国家归档显示，不根据姓名推测。</div></div>`}
function players(){return `<div class="page"><div class="page-head"><div><div class="kicker">PLAYERS</div><h1>选手列表</h1><p>按照四大赛区筛选，ID 后直接显示国籍。</p></div></div><div class="player-table">${Object.entries(D.rosters).flatMap(([t,ps])=>ps.map((p,i)=>`<div class="player-row"><img src="${logo(t)}"><div><b>${esc(p)}</b><small>${esc(t)}</small></div><span>${['TOP','JUG','MID','ADC','SUP'][i]||'PLAYER'}</span><strong>${esc(country(t,p))}</strong></div>`)).join('')}</div></div>`}
function rankings(){return `<div class="page"><div class="page-head"><div><div class="kicker">POWER RANKINGS</div><h1>战力排名</h1><p>展示档案中的战力积分，不将其解释为预测或评价。</p></div></div><div class="ranking-table">${[['NRG','3018'],['E1 Esports','2840'],['MIC GAMING','2736'],['G2 ESPORTS','1500'],['PaperRex','1438'],['Bilibili Gaming','1280']].map((x,i)=>`<div class="rank-big"><b>${i+1}</b>${T(x[0])}<span>${x[1]}</span></div>`).join('')}</div></div>`}
function generatedSchedule(e){const teams=(e.teams||[]).map(teamName);let pool=[...new Set([...teams,...Object.values(D.teams).flat()])].filter(Boolean);let extras=pool.filter(x=>x!==teamName(e.champion)&&x!==teamName(e.runner));extras=extras.slice(0,6);while(extras.length<6)extras.push('TBD');const c=teamName(e.champion),r=teamName(e.runner),q=[{a:c,b:extras[0],s:'2:0'},{a:extras[1],b:extras[2],s:'1:2'},{a:r,b:extras[3],s:'2:1'},{a:extras[4],b:extras[5],s:'0:2'}];return {q,semi:[{a:c,b:extras[2],s:'3:1'},{a:r,b:extras[5],s:'3:2'}],final:{a:c,b:r,s:e.finalScore}}}
function bracket(e){const g=generatedSchedule(e);return `<div class="bracket"><div><h3>四分之一决赛</h3>${g.q.map((m,i)=>`<div class="bracket-match"><small>QF${i+1} · BO5</small><div>${T(m.a)}<b>${m.s.split(':')[0]}</b></div><div>${T(m.b)}<b>${m.s.split(':')[1]}</b></div></div>`).join('')}</div><div><h3>半决赛</h3>${g.semi.map((m,i)=>`<div class="bracket-match"><small>SF${i+1} · BO5</small><div>${T(m.a)}<b>${m.s.split(':')[0]}</b></div><div>${T(m.b)}<b>${m.s.split(':')[1]}</b></div></div>`).join('')}</div><div><h3>总决赛</h3><div class="bracket-match final"><small>FINAL · BO5</small><div>${T(g.final.a)}<b>${g.final.s.split(':')[0]}</b></div><div>${T(g.final.b)}<b>${g.final.s.split(':')[1]}</b></div><strong>冠军 · ${esc(g.final.a)}</strong></div></div></div>`}
function event(id){const e=D.international.find(x=>x.id===id);if(!e)return historyEvent(id);return `<div class="page"><div class="event-hero"><div><div class="kicker">${e.year} · ${esc(e.type||'INTERNATIONAL')}</div><h1>${esc(e.name)}</h1><p>${esc(e.city||'')}　·　${esc(e.date||'')}</p></div><div class="winner">${T(e.champion)}<strong>${esc(e.finalScore||'—')}</strong>${T(e.runner)}</div></div><div class="event-tabs"><span>概览</span><span>赛程</span><span>对阵图</span><span>战队</span></div><div class="section-title"><h2>决赛</h2></div><div class="final-card">${T(e.champion)}<strong>${esc(e.finalScore||'—')}</strong>${T(e.runner)}</div><div class="section-title"><h2>完整对阵图</h2><small>冠军/亚军与决赛比分来自档案；其余场次按档案赛制补全。</small></div>${bracket(e)}<div class="section-title"><h2>赛事赛程</h2></div><div class="schedule-table">${['开赛日','瑞士轮第1轮','瑞士轮第2轮','瑞士轮第3轮','胜者组半决赛','败者组半决赛','胜者组决赛','败者组决赛','总决赛'].map((s,i)=>`<div><span>${s}</span><b>${i<4?'4 场 BO3':i===8?'1 场 BO5':'1–2 场 BO5'}</b><em>${e.year}-${String((i%9)+1).padStart(2,'0')}-${String((i+1)).padStart(2,'0')}</em></div>`).join('')}</div></div>`}
function historyEvent(id){const idx=Number(id.replace('hist-',''));const e=D.historyEvents[idx];if(!e)return `<div class="page"><h1>未找到赛事</h1></div>`;const pseudo={...e,id,name:e.name,type:'全球赛事',city:e.city,teams:[e.champion,e.runner,...Object.values(D.teams).flat().filter(t=>t!==e.champion&&t!==e.runner).slice(0,6)],format:'历史赛事赛程按档案赛制结构补全'};return eventFromHistory(pseudo)}
function eventFromHistory(e){return `<div class="page"><div class="event-hero"><div><div class="kicker">${e.year} · PAST CHAMPION</div><h1>${esc(e.city)} · 全球赛事</h1><p>冠军档案：${esc(e.champion)}　${esc(e.finalScore)}　${esc(e.runner)}</p></div><div class="winner">${T(e.champion)}<strong>${esc(e.finalScore)}</strong>${T(e.runner)}</div></div><div class="section-title"><h2>赛事对阵表</h2><small>最终结果严格采用你提供的档案；历史档案没有逐场记录的部分，按该赛事赛制补全。</small></div>${bracket({teams:e.teams,champion:e.champion,runner:e.runner,finalScore:e.finalScore})}<div class="section-title"><h2>完整赛程</h2></div><div class="schedule-table">${['揭幕赛 01','揭幕赛 02','揭幕赛 03','揭幕赛 04','半决赛 01','半决赛 02','总决赛'].map((s,i)=>`<div><span>${s}</span><b>${i===6?'BO5':'BO3 / BO5'}</b><em>${e.year} · M${i+1}</em></div>`).join('')}</div></div>`}
function history(){const years=[...new Set(D.historyEvents.map(e=>e.year))].sort((a,b)=>b-a);const h=location.hash.split('?')[1]||'';const y=new URLSearchParams(h).get('year');const year=y?Number(y):years[0];const events=D.historyEvents.filter(e=>e.year===year);return `<div class="page"><div class="page-head"><div><div class="kicker">PAST CHAMPION</div><h1>历史冠军</h1><p>点击年份，直接展开该年度全部全球赛事、冠军、亚军、决赛比分和对阵表。</p></div></div><div class="year-tabs">${years.map(x=>`<a class="${x===year?'on':''}" href="#/history?year=${x}">${x}</a>`).join('')}</div><div class="history-layout"><div class="history-list">${events.map((e,i)=>`<a href="#/history-event/${D.historyEvents.indexOf(e)}" class="history-card"><b>${e.city}</b><span>全球赛事 · ${e.year}</span><div>${T(e.champion)}<strong>${e.finalScore}</strong>${T(e.runner)}</div></a>`).join('')}</div><div class="history-info"><h3>${year} 赛事总览</h3><p>${events.length} 场全球赛事记录</p><div class="champion-list">${events.map(e=>`<div><small>${e.city}</small><b>${e.champion}</b><span>${e.finalScore}</span><i>${e.runner}</i></div>`).join('')}</div></div></div></div>`}
function about(){return `<div class="page"><div class="page-head"><div class="kicker">TPA ESPORTS DATABASE</div><h1>关于本站</h1><p>本站是基于你提供的《TPA战队档案》制作的静态赛事数据库。</p></div><div class="notice large">数据原则：冠军、亚军、决赛比分、战队和选手名单以档案为主。历史档案未逐场列出的对阵，本站按照你要求生成完整可视化赛程；生成场次不会覆盖档案中的最终冠军、亚军和决赛比分。</div></div>`}
function router(){const p=location.hash.slice(1)||'/';if(p.startsWith('/event/'))shell(event(p.split('/')[2]));else if(p.startsWith('/history-event/'))shell(historyEvent(p.split('/')[2]));else if(p.startsWith('/team/'))shell(team(decodeURIComponent(p.split('/')[2])));else if(p.startsWith('/history'))shell(history());else if(p.startsWith('/events'))shell(events());else if(p.startsWith('/schedule'))shell(schedule());else if(p.startsWith('/teams'))shell(teams());else if(p.startsWith('/players'))shell(players());else if(p.startsWith('/rankings'))shell(rankings());else if(p.startsWith('/about'))shell(about());else shell(home())}window.addEventListener('hashchange',router);router();